# Creating MLflow deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codification-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codification-api
  template:
    metadata:
      labels:
        app: codification-api
    spec:
      containers:
        - name: api
          image: inseefrlab/formation-mlops-api:init-src
          imagePullPolicy: Always
          env:
            - name: MLFLOW_S3_ENDPOINT_URL
              value: https://minio.lab.sspcloud.fr
            - name: MLFLOW_TRACKING_URI
              value: https://projet-formation-912310.user.lab.sspcloud.fr
            - name: MLFLOW_MODEL_NAME
              value: fasttext
            - name: MLFLOW_MODEL_VERSION
              value: "5"
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          resources:
            requests:
              memory: "2Gi"
              cpu: "1000m"
            limits:
              memory: "5Gi"
              cpu: "10000m"
