# Creating MLflow deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codification-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codification-api
  template:
    metadata:
      labels:
        app: codification-api
    spec:
      containers:
        - name: api
          image: inseefrlab/formation-mlops:main
          imagePullPolicy: Always
          env:
            - name: MLFLOW_TRACKING_URI
              value: https://user-tfaria-144695.user.lab.sspcloud.fr
            - name: MLFLOW_MODEL_NAME
              value: fasttext
            - name: MLFLOW_MODEL_VERSION
              value: "3"
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
