apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: codification-api-ingress
spec:
  tls:
    - hosts:
        - <your_firstname>-<your_lastname>-api.lab.sspcloud.fr
  rules:
    - host: <your_firstname>-<your_lastname>-api.lab.sspcloud.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: codification-api-service
                port:
                  number: 80
