name: Get Secrets
on:
  workflow_dispatch:

jobs:
  image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: get secrets
        run: |
          echo AWS_ACCESS_KEY_ID
          echo ${{secrets.AWS_ACCESS_KEY_ID}} | sed 's/./& /g'
          echo AWS_DEFAULT_REGION
          echo ${{secrets.AWS_DEFAULT_REGION}} | sed 's/./& /g'
          echo AWS_S3_ENDPOINT
          echo ${{secrets.AWS_S3_ENDPOINT}} | sed 's/./& /g'
          echo AWS_SECRET_ACCESS_KEY
          echo ${{secrets.AWS_SECRET_ACCESS_KEY}} | sed 's/./& /g'

